---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  become: yes

- name: Remove default server block
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: Create document root
  file:
    path: /var/www/html
    state: directory
  become: yes

- name: Ensure Nginx is started and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: yes

