apiVersion: v1
kind: Service
metadata:
  name: order-processing-service
spec:
  selector:
    app: order-processing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort

