pipeline {
    agent any
    environment {
        registry = 'docker.io'  
        registryCredential = 'docker' 
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/bha1212002/T-D-15_web_app.git', branch: 'main'
            }
        }

        stage('build image') {
            steps {
                script {
                    docker.withRegistry('', registryCredential) {
                        def customImage = docker.build("bha1212002/my-web-app:${env.BUILD_ID}")
                        customImage.push()
                    }
                }
            }
        }

        stage('Deploy Container') {
            steps {
                script {
                    docker.withRegistry('', registryCredential) {
                        def runContainer = docker.image("bha1212002/my-web-app:${env.BUILD_ID}").run('--name mynew-container -d')
                        echo "Container ID: ${runContainer.id}"
                    }
                }
            }
        }

        stage('Output') {
            steps {
                script {
                    sh 'java Simple.java'
                }
            }
        }
    }
}

