apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-processing
  template:
    metadata:
      labels:
        app: order-processing
    spec:
      containers:
      - name: order-processing
        image: bhavik1212/order-processing
        ports:
        - containerPort: 5001

